// export const metadata = {
//   title: "Sanz Clima full stack test",
//   description: "Generated by Next.js",
// };

import Link from "next/link";

const links = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "Calc",
    route: "/calc",
  },
  {
    label: "History",
    route: "/history",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Sanz Clima full stack test</title>
      </head>
      <body>
        <header>
          <nav>
            <ul>
              {links.map(({ label, route }) => (
                <li key={route}>
                  <Link href={route}>{label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
